server:
    port: 1010

spring:
    application:
        name: authorization-server
    profiles:
        active: local
    config:
        import:
            - security/application-authorization.yml
